### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by garethtdavies** [jrwashburn/mina-pool-payout#144]
Get this error running for a large pool B62qpge4uMq4Vv5Rvc8Gw9qSquUYd6xoW1pz7HQkMSHm6h1o7pvLPAN

```
npm run payout -- -e 0 -f 1 > output
/Users/garethtdavies/Documents/projects/mina-pool-payout/src/core/transaction/TransactionProcessor.ts:38
    this.fileWriter.write(payoutDetailsFileName, JSON.stringify(payoutDetails));
                                                      ^
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at TransactionProcessor.write (/Users/garethtdavies/Documents/projects/mina-pool-payout/src/core/transaction/TransactionProcessor.ts:38:55)
    at PaymentProcessor.run (/Users/garethtdavies/Documents/projects/mina-pool-payout/src/core/payment/PaymentProcessor.ts:33:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by jrwashburn** [comment]
Will need to batch things probably. I'll run few a through epochs with LPAN and see what else it breaks.

**Comment by jrwashburn** [comment]
Will just update to stream - but then need to also change the hash calculation as well. Should have a new version tonight.
