### ISSUE TITLE
bug: handle null coinbasereceiver from mina explorer

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#79]
firerydev reported failures to payout for two addresses using mina explorer datasource. Issue identified 43 transactions that have null coinbase receiver, which can occur when the coinbase is 0 for the block. The null is handled for archived, but not mina explorer data.  (Fails at https://github.com/jrwashburn/mina-pool-payout/blob/4fc8875cd0becc20e07787ed8767439e7305a1a5/src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts#L115 : 

`TypeError: Cannot read property 'publicKey' of null
    at /Users/jrwashburn/mina/mina-pool-payout/src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts:125:73
    at Array.map (<anonymous>)
    at Object.getBlocks (/Users/jrwashburn/mina/mina-pool-payout/src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts:115:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MinaExplorerBlockDataProvider.getBlocks (/Users/jrwashburn/mina/mina-pool-payout/src/core/dataProvider/MinaExplorerBlockDataProvider.ts:13:16)
    at PaymentBuilder.build (/Users/jrwashburn/mina/mina-pool-payout/src/core/payment/PaymentBuilder.ts:46:32)
    at PaymentProcessor.run `(/Users/jrwashburn/mina/mina-pool-payout/src/core/payment/PaymentProcessor.ts:39:34)`
`

**Comment by jrwashburn** [comment]
Closed / resolved.
